In [1]:
import pandas as pd
import json

# Load dataset
df = pd.read_csv("final_dataset_11k.csv")

df.head()

,trans_date_trans_time,cc_num,merchant,category,amt,city,state,city_pop,is_fraud
0,2019-07-13 09:40:49,2713913904780408,fraud_Torp-Lemke,misc_pos,3.94,Delhi,LA,6581,0
1,2019-03-03 20:31:59,2291163933867244,fraud_Windler LLC,kids_pets,96.95,Columbia,SC,333497,0
2,2020-02-05 16:38:28,3518234918950662,fraud_Schiller Ltd,personal_care,174.42,Sherman,TX,46563,0
3,2020-05-09 12:33:47,3589255887819806,fraud_Terry-Huel,shopping_net,2.54,Hancock,MD,3766,0
4,2019-12-12 12:41:42,30235438713303,"fraud_Nitzsche, Kessler and Wolff",shopping_pos,3.32,Winfield,WV,5512,0

In [2]:
# Convert to datetime
df["trans_date_trans_time"] = pd.to_datetime(df["trans_date_trans_time"])

# Extract hour (0–23)
df["trans_hour"] = df["trans_date_trans_time"].dt.hour

# Extract day of week (Monday=0 → Sunday=6)
# Convert to 1–7 format (Monday=1, Sunday=7)
df["day_of_week"] = df["trans_date_trans_time"].dt.dayofweek + 1

df[["trans_hour", "day_of_week"]].head()

   trans_hour  day_of_week
0           9            6
1          20            7
2          16            3
3          12            6
4          12            4

In [3]:
required_columns = [
    "merchant",
    "category",
    "amt",
    "city",
    "state",
    "city_pop",
    "trans_hour",
    "day_of_week",
    "is_fraud"
]

df_final = df[required_columns]

In [4]:
df_sample = df_final.sample(n=1000, random_state=42).reset_index(drop=True)

df_sample.head()

,merchant,category,amt,city,state,city_pop,trans_hour,day_of_week,is_fraud
0,fraud_Wolf Inc,grocery_pos,93.87,Helm,CA,123,1,6,0
1,"fraud_Reichert, Huels and Hoppe",shopping_net,89.16,Cokeburg,PA,632,0,5,0
2,"fraud_Turner, Ziemann and Lehner",food_dining,145.73,Cuyahoga Falls,OH,47772,3,6,0
3,fraud_Weber and Sons,food_dining,2.43,Sacramento,CA,757530,16,1,0
4,fraud_Torp-Lemke,misc_pos,8.50,Detroit,MI,673342,12,1,0

In [5]:
df_with_label = df_sample.copy()

df_with_label.to_json("fraud_test_data_with_label.json", orient="records", indent=4)

In [6]:
df_without_label = df_sample.drop(columns=["is_fraud"])

df_without_label.to_json("fraud_test_data_without_label.json", orient="records", indent=4)

In [7]:
print(json.dumps(df_without_label.iloc[0].to_dict(), indent=4))

{
    "merchant": "fraud_Wolf Inc",
    "category": "grocery_pos",
    "amt": 93.87,
    "city": "Helm",
    "state": "CA",
    "city_pop": 123,
    "trans_hour": 1,
    "day_of_week": 6
}

In [8]:
df_with_label.to_csv("fraud_test_data_with_label.csv", index=False)
df_without_label.to_csv("fraud_test_data_without_label.csv", index=False)

In [9]:
import pandas as pd

# Load dataset
df = pd.read_csv("final_dataset_11k.csv")

# Take first 15 rows
df_15 = df.head(15)

# Save to new CSV
df_15.to_csv("sample_15_rows.csv", index=False)

print("Saved successfully as sample_15_rows.csv")

Saved successfully as sample_15_rows.csv